import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for this project's documentation.
 * One autogenerated tree over everything under docs/. Numeric filename
 * prefixes (01-, 02-, …) drive ordering; replace this with an explicit
 * structure if you want to control it by hand.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
